### ISSUE TITLE
Make wave support optional untill boyhagemann/Wave has a stable release

### ISSUE THREAD

**Issue by AJenbo** [wapmorgan/MediaFile#3]
Currently the boyhagemann/Wave package is blocking the installation of this package unless forced or one changes there policy to accept dev packages.

boyhagemann hasn't responded to the request to do so for nearly a year and there has been no development since 2013.

A way around this would be to make wave support optional and not include the package by default. I for one don't need wave support and I would much rather use this libery then getID3, both for speed and and I have very little trust in there code as it's a big mess.

**Comment by wapmorgan** [comment]
Sorry for late response! Fixed it in **0.1.4** version.

**Comment by AJenbo** [comment]
Nice
