### ISSUE TITLE
Can't read a video/mov file

### ISSUE THREAD

**Issue by tacman** [wapmorgan/MediaFile#5]
When trying to open this file, I get 

```
In MediaFile.php line 42:

  File "C:\Users\tacma\OneDrive\Pictures\JUFJ\Amanda\amanda--1.MOV" is not a supported video/audio, it's "video/mov"!
```

**Comment by tacman** [comment]
[3-second-test.zip](https://github.com/wapmorgan/MediaFile/files/2472883/3-second-test.zip)

This isn't really a zip file, please rename it to .MOV and try to opening it with 

            $media = MediaFile::open($filename);

I'm on a new computer and having issues with zip, and github won't let me upload a .MOV file, thus the silly renaming.

**Comment by tacman** [comment]
can  I help out in some way to fix this?  ffprobe works on the file.

**Comment by wapmorgan** [comment]
Oh, I missed to check. `MOV`-format is not supported at the moment.
https://github.com/wapmorgan/MediaFile/blob/master/README.md#supported-formats
