### ISSUE TITLE
MP3 file generates exception

### ISSUE THREAD

**Issue by fgilio** [wapmorgan/MediaFile#7]
Hello!
I have an MP3 file which is generating an `Unknown format for file "/tmp/phpaa3d76"!` exception, but works ok in other players and macOS recognizes it without any problem.
I later tried to fix it using using [this tool](https://mp3repair.net/en/) and now it work just fine.

In the archive I'm sharing bot MP3s, the original and the fixed one: [Archive.zip](https://github.com/wapmorgan/MediaFile/files/3616899/Archive.zip)

Maybe this can be handled in the library and the exception avoided.

**Comment by wapmorgan** [comment]
Update MediaFile and dependencies (`composer update`) to latest versions and try again.

**Comment by fgilio** [comment]
I'm using `0.1.4`, which I think is the latest version

**Comment by wapmorgan** [comment]
That's problem in filetypedetector, it can not detect mp3 file without extension and id3v2 tag in the file beginning, so fails. It requires update, so in future update.

**Comment by fgilio** [comment]
Do you want me to open the issue in that repo?

**Comment by wapmorgan** [comment]
No, this file has some garbage in it's the beginning. That's not normal file. Fixing this is really hard at this moment.

**Comment by fgilio** [comment]
👍 should we just close this issue then?
